# FROM php:8.1.18-apache-bullseye
FROM php:8.0-apache
# RUN echo "<?php phpinfo(); ?>" > /var/www/html/info.php && \
#     echo '<h1> Hi Chandra this is KrishnaPrasad </h1>' > /var/www/html/test.html
ADD ./info.php /var/www/html/info.php
ADD ./test.html /var/www/html/krishna.html
EXPOSE 80